# -*- coding: utf-8 -*-
"""MoodMind_AI_Project

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1QKXnL026VKkX4BB3NkBz73WlPmSTAKhF
"""



from transformers import pipeline
import gradio as gr

emotion_classifier = pipeline(
    "text-classification",
    model="j-hartmann/emotion-english-distilroberta-base",
    top_k=1
)

def moodmind_ai(user_input):

    result = emotion_classifier(user_input)

    emotion = result[0][0]['label']
    score = round(result[0][0]['score'] * 100, 2)

    # Study suggestions
    if emotion == "sadness":
        advice = """
📘 Study Plan:
- Study 25 mins
- Take 5 min breaks
- Listen to calm music
- Sleep early
"""

    elif emotion == "joy":
        advice = """
🚀 Study Plan:
- Best time for hard subjects
- Practice mock tests
- Revise quickly
"""

    elif emotion == "anger":
        advice = """
🧘 Study Plan:
- Deep breathing for 5 mins
- Avoid difficult topics first
- Start with easy subjects
"""

    elif emotion == "fear":
        advice = """
📅 Study Plan:
- Make small goals
- Avoid overthinking
- Focus chapter by chapter
"""

    else:
        advice = """
📚 Study Plan:
- Balanced study schedule
- Maintain consistency
"""

    return f"""
Detected Emotion: {emotion}

Confidence Score: {score}%

{advice}
"""

interface = gr.Interface(
    fn=moodmind_ai,
    inputs=gr.Textbox(
        lines=4,
        placeholder="Type how you feel and your study situation..."
    ),
    outputs="text",
    title="MoodMind AI",
    description="AI-powered Emotion Based Study Planner"
)

interface.launch()

def moodmind_ai(user_input):

    result = emotion_classifier(user_input)

    emotion = result[0][0]['label']
    score = round(result[0][0]['score'] * 100, 2)

    # Productivity score
    productivity = 100 - int(score / 2)

    # Study suggestions
    if emotion == "sadness":
        advice = """
📘 Study Plan:
- Study 25 mins
- Take 5 min breaks
- Listen to calm music
- Sleep early
"""

    elif emotion == "joy":
        advice = """
🚀 Study Plan:
- Best time for hard subjects
- Practice mock tests
- Revise quickly
"""

    elif emotion == "anger":
        advice = """
🧘 Study Plan:
- Deep breathing for 5 mins
- Avoid difficult topics first
- Start with easy subjects
"""

    elif emotion == "fear":
        advice = """
📅 Study Plan:
- Make small goals
- Avoid overthinking
- Focus chapter by chapter
"""

    else:
        advice = """
📚 Study Plan:
- Balanced study schedule
- Maintain consistency
"""

    return f"""
Detected Emotion: {emotion}

Confidence Score: {score}%

Productivity Score: {productivity}%

{advice}
"""

interface.launch()

def moodmind_ai(user_input):

    result = emotion_classifier(user_input)

    emotion = result[0][0]['label']
    score = round(result[0][0]['score'] * 100, 2)

    # Productivity score
    productivity = 100 - int(score / 2)

    # Quotes
    quotes = {
        "sadness": "Small progress is still progress.",
        "fear": "Consistency beats anxiety.",
        "joy": "Use today's energy wisely.",
        "anger": "Calm mind creates better results."
    }

    quote = quotes.get(emotion, "Keep moving forward.")

    # Study suggestions
    if emotion == "sadness":
        advice = """
📘 Study Plan:
- Study 25 mins
- Take 5 min breaks
- Listen to calm music
- Sleep early
"""

    elif emotion == "joy":
        advice = """
🚀 Study Plan:
- Best time for hard subjects
- Practice mock tests
- Revise quickly
"""

    elif emotion == "anger":
        advice = """
🧘 Study Plan:
- Deep breathing for 5 mins
- Avoid difficult topics first
- Start with easy subjects
"""

    elif emotion == "fear":
        advice = """
📅 Study Plan:
- Make small goals
- Avoid overthinking
- Focus chapter by chapter
"""

    else:
        advice = """
📚 Study Plan:
- Balanced study schedule
- Maintain consistency
"""

    return f"""
Detected Emotion: {emotion}

Confidence Score: {score}%

Productivity Score: {productivity}%

Motivation:
{quote}

{advice}
"""

interface.launch()

interface = gr.Interface(
    fn=moodmind_ai,

    inputs=gr.Textbox(
        lines=4,
        placeholder="Example: I am stressed about exams..."
    ),

    outputs=gr.Textbox(),

    title="🧠 MoodMind AI",

    description="""
AI-powered Emotion Based Study Planner
Analyze emotions and get smart study advice instantly.
""",

    theme="soft"
)

interface.launch()

model="cardiffnlp/twitter-xlm-roberta-base-sentiment"

interface = gr.Interface(
    fn=moodmind_ai,

    inputs=[
        gr.Textbox(label="Your Name"),
        gr.Number(label="Days Left For Exam"),
        gr.Number(label="Sleep Hours"),
        gr.Number(label="Study Hours Per Day"),
        gr.Slider(1,10,label="Stress Level"),
        gr.Textbox(lines=4,label="How are you feeling?")
    ],

    outputs="text",

    title="🧠 MoodMind AI Pro",

    description="Real-Time AI Productivity & Wellness Assistant",

    theme="soft"
)

from datetime import datetime

def moodmind_ai(name, exam_days, sleep_hours, study_hours, stress_level, user_input):

    # Current time
    current_time = datetime.now().strftime("%d-%m-%Y %H:%M:%S")

    # Emotion detection
    result = emotion_classifier(user_input)

    emotion = result[0][0]['label']
    score = round(result[0][0]['score'] * 100, 2)

    # Productivity score
    productivity = 100 - int(score / 2)

    # Quotes
    quotes = {
        "sadness": "Small progress is still progress.",
        "fear": "Consistency beats anxiety.",
        "joy": "Use today's energy wisely.",
        "anger": "Calm mind creates better results."
    }

    quote = quotes.get(emotion, "Keep moving forward.")

    # Health warning
    if sleep_hours < 5:
        health_warning = "⚠️ Low sleep may reduce productivity."
    else:
        health_warning = "✅ Sleep schedule looks okay."

    # Exam urgency
    if exam_days <= 3:
        urgency = "🔥 High Priority Preparation Time"

    elif exam_days <= 7:
        urgency = "⏳ Moderate Exam Pressure"

    else:
        urgency = "📘 You still have preparation time."

    # Study feedback
    if study_hours >= 8:
        study_feedback = "🚀 Excellent dedication."

    elif study_hours >= 4:
        study_feedback = "👍 Good consistency."

    else:
        study_feedback = "📚 Increase study time gradually."

    # Advice
    if emotion == "sadness":
        advice = """
📘 Study Plan:
- Study 25 mins
- Take 5 min breaks
- Listen to calm music
"""

    elif emotion == "joy":
        advice = """
🚀 Study Plan:
- Practice mock tests
- Revise difficult topics
"""

    elif emotion == "fear":
        advice = """
📅 Study Plan:
- Focus chapter by chapter
- Avoid overthinking
"""

    else:
        advice = """
📚 Study Plan:
- Maintain consistency
"""

    return f"""
🧠 MoodMind AI Pro Report

🕒 Generated Time:
{current_time}

👤 Name: {name}

😊 Emotion: {emotion}

📊 Confidence Score: {score}%

⚡ Productivity Score: {productivity}%

😰 Stress Level: {stress_level}/10

📅 Exam Countdown: {exam_days} days

😴 Sleep Hours: {sleep_hours}

📚 Study Hours: {study_hours}

{health_warning}

{urgency}

{study_feedback}

💡 Motivation:
{quote}

{advice}
"""

interface = gr.Interface(
    fn=moodmind_ai,

    inputs=[
        gr.Textbox(label="Your Name"),
        gr.Number(label="Days Left For Exam"),
        gr.Number(label="Sleep Hours"),
        gr.Number(label="Study Hours Per Day"),
        gr.Slider(1,10,label="Stress Level"),
        gr.Textbox(lines=4,label="How are you feeling?")
    ],

    outputs="text",

    title="🧠 MoodMind AI Pro",

    description="Real-Time AI Productivity & Wellness Assistant",

    theme="soft"
)

interface.launch()

interface = gr.Interface(
    fn=moodmind_ai,

    inputs=[
        gr.Textbox(
            label="Your Name"
        ),

        gr.Number(
            label="Days Left For Exam"
        ),

        gr.Number(
            label="Sleep Hours"
        ),

        gr.Number(
            label="Study Hours Per Day"
        ),

        gr.Slider(
            1,
            10,
            label="Stress Level"
        ),

        gr.Textbox(
            lines=6,
            placeholder="Describe your feelings, study pressure, exams, goals...",
            label="How are you feeling?"
        )
    ],

    outputs=gr.Textbox(
        lines=30,
        label="MoodMind AI Pro Report"
    ),

    title="🧠 MoodMind AI Pro",

    description="""
Real-Time AI Productivity & Wellness Assistant
""",

    theme="soft"
)

interface.launch()

!pip install transformers gradio matplotlib fpdf

from transformers import pipeline
import gradio as gr
from datetime import datetime
import matplotlib.pyplot as plt
from fpdf import FPDF

!pip install transformers gradio matplotlib fpdf

emotion_classifier = pipeline(
    "text-classification",
    model="cardiffnlp/twitter-xlm-roberta-base-sentiment"
)

def moodmind_ai(name, exam_days, sleep_hours, study_hours, stress_level, user_input):

    current_time = datetime.now().strftime("%d-%m-%Y %H:%M:%S")

    result = emotion_classifier(user_input)

    emotion = result[0]['label']
    score = round(result[0]['score'] * 100, 2)

    productivity = 100 - int(stress_level * 5)

    quotes = {
        "LABEL_0": "Stay calm and trust yourself.",
        "LABEL_1": "Small progress is still progress.",
        "LABEL_2": "Use today's energy wisely."
    }

    quote = quotes.get(emotion, "Keep moving forward.")

    if sleep_hours < 5:
        health_warning = "⚠️ Low sleep may affect concentration."
    else:
        health_warning = "✅ Sleep schedule looks healthy."

    if exam_days <= 3:
        urgency = "🔥 High Exam Pressure"

    elif exam_days <= 7:
        urgency = "⏳ Moderate Exam Pressure"

    else:
        urgency = "📘 Enough time available."

    if study_hours >= 8:
        study_feedback = "🚀 Excellent dedication."

    elif study_hours >= 4:
        study_feedback = "👍 Good consistency."

    else:
        study_feedback = "📚 Increase study hours gradually."

    report = f'''
🧠 MoodMind AI Pro Report

🕒 Generated Time:
{current_time}

👤 Name: {name}

😊 Emotion: {emotion}

📊 Confidence Score: {score}%

⚡ Productivity Score: {productivity}%

😰 Stress Level: {stress_level}/10

📅 Exam Countdown: {exam_days} days

😴 Sleep Hours: {sleep_hours}

📚 Study Hours: {study_hours}

{health_warning}

{urgency}

{study_feedback}

💡 Motivation:
{quote}
'''

    return report

interface = gr.Interface(
    fn=moodmind_ai,

    inputs=[

        gr.Textbox(
            label="👤 Your Name"
        ),

        gr.Number(
            label="📅 Days Left For Exam"
        ),

        gr.Number(
            label="😴 Sleep Hours"
        ),

        gr.Number(
            label="📚 Study Hours Per Day"
        ),

        gr.Slider(
            1,
            10,
            label="😰 Stress Level"
        ),

        gr.Textbox(
            lines=6,
            placeholder="Describe your emotions, stress, exams, goals...",
            label="🧠 How are you feeling?"
        )
    ],

    outputs=gr.Textbox(
        lines=28,
        label="📋 AI Wellness Report"
    ),

    title="🧠 MoodMind AI Pro",

    description="Real-Time AI Productivity & Wellness Assistant",

    theme="soft"
)

interface.launch()

!pip install requests pandas plotly

import requests
import pandas as pd
import plotly.express as px

city = "Nellore"

weather_url = f"https://wttr.in/{city}?format=j1"

weather_data = requests.get(weather_url).json()

temperature = weather_data['current_condition'][0]['temp_C']

weather_desc = weather_data['current_condition'][0]['weatherDesc'][0]['value']

from transformers import pipeline
import gradio as gr
from datetime import datetime
import requests
import pandas as pd
import plotly.express as px
from fpdf import FPDF # Import FPDF

# Load AI model

emotion_classifier = pipeline(
    "text-classification",
    model="cardiffnlp/twitter-xlm-roberta-base-sentiment"
)

# Main function

def moodmind_ai(name, exam_days, sleep_hours, study_hours, stress_level, user_input):

    current_time = datetime.now().strftime("%d-%m-%Y %H:%M:%S")

    # Emotion Detection
    result = emotion_classifier(user_input)

    emotion = result[0]['label']
    score = round(result[0]['score'] * 100, 2)

    # Productivity
    productivity = 100 - int(stress_level * 5)

    # Weather
    city = "Nellore"

    weather_url = f"https://wttr.in/{city}?format=j1"

    weather_data = requests.get(weather_url).json()

    temperature = weather_data['current_condition'][0]['temp_C']

    weather_desc = weather_data['current_condition'][0]['weatherDesc'][0]['value']

    # Future Prediction
    if sleep_hours >= 7 and study_hours >= 5:
        future_prediction = "📈 High productivity expected."

    elif stress_level >= 8:
        future_prediction = "⚠️ Burnout risk detected."

    else:
        future_prediction = "📊 Moderate productivity expected."

    # Wellness Status
    wellness_score = (
        sleep_hours * 10
        + study_hours * 5
        - stress_level * 7
    )

    if wellness_score > 80:
        wellness_status = "🌟 Excellent"

    elif wellness_score > 50:
        wellness_status = "👍 Stable"

    else:
        wellness_status = "⚠️ Needs Attention"

    # Motivation
    if emotion == "LABEL_0":
        quote = "Stay calm and trust yourself."

    elif emotion == "LABEL_1":
        quote = "Small progress is still progress."

    else:
        quote = "Use today's energy wisely."

    # Recommendation
    if stress_level >= 8:
        recommendation = "Reduce study overload and rest properly."

    elif study_hours < 3:
        recommendation = "Increase study consistency gradually."

    else:
        recommendation = "Maintain your current momentum."

    # Chart
    data = pd.DataFrame({
        "Category": ["Sleep", "Study", "Stress"],
        "Value": [sleep_hours, study_hours, stress_level]
    })

    fig = px.bar(
        data,
        x="Category",
        y="Value",
        title="MoodMind Analytics"
    )

    # Final Report
    report = f"""

🧠 MoodMind AI Pro Report

🕒 Current Time:
{current_time}

👤 Name:
{name}

🌤️ Weather:
{temperature}°C, {weather_desc}

😊 Emotion:
{emotion}

📊 Confidence Score:
{score}%

⚡ Productivity Score:
{productivity}%

🔮 Future Prediction:
{future_prediction}

🧠 Wellness Status:
{wellness_status}

😰 Stress Level:
{stress_level}/10

📅 Exam Countdown:
{exam_days} days

😴 Sleep Hours:
{sleep_hours}

📚 Study Hours:
{study_hours}

💡 Motivation:
{quote}

🚀 Recommendation:
{recommendation}


"""

    # Generate PDF
    pdf = FPDF()
    pdf.add_page()
    pdf.set_font("Arial", size=12)

    # FPDF only supports Latin-1 encoding, so we need to encode and decode
    clean_report = report.encode("latin-1", "ignore").decode("latin-1")

    pdf.multi_cell(0, 10, clean_report)

    pdf_file = "MoodMind_Report.pdf"
    pdf.output(pdf_file)

    return report, fig, pdf_file

# Interface

interface = gr.Interface(

    fn=moodmind_ai,

    inputs=[

        gr.Textbox(label="👤 Your Name"),

        gr.Number(label="📅 Days Left For Exam"),

        gr.Number(label="😴 Sleep Hours"),

        gr.Number(label="📚 Study Hours Per Day"),

        gr.Slider(
            minimum=1,
            maximum=10,
            label="😰 Stress Level"
        ),

        gr.Textbox(
            lines=6,
            label="🧠 How are you feeling?",
            placeholder="Describe your emotions, exams, goals..."
        )
    ],

    outputs=[

        gr.Textbox(
            lines=30,
            label="📋 AI Report"
        ),

        gr.Plot(
            label="📊 Analytics"
        ),
        gr.File(label="Download Report PDF") # Add File output for PDF
    ],

    title="🧠 MoodMind AI Pro",

    description="Real-Time AI Productivity & Wellness Dashboard",

    theme="soft"

)

# Launch

interface.launch()

from transformers import pipeline
import gradio as gr
from datetime import datetime
import requests
import pandas as pd
import plotly.express as px
from fpdf import FPDF

# Load AI Model

emotion_classifier = pipeline(
"text-classification",
model="cardiffnlp/twitter-xlm-roberta-base-sentiment"
)

# Main Function

def moodmind_ai(name, exam_days, sleep_hours, study_hours, stress_level, user_input):

# Current Time
    current_time = datetime.now().strftime("%d-%m-%Y %H:%M:%S")

# Emotion Detection
    result = emotion_classifier(user_input)

    emotion = result[0]['label']
    score = round(result[0]['score'] * 100, 2)

# Productivity
    productivity = 100 - int(stress_level * 5)

# Real-Time Weather
    city = "Nellore"

    weather_url = f"https://wttr.in/{city}?format=j1"

    weather_data = requests.get(weather_url).json()

    temperature = weather_data['current_condition'][0]['temp_C']

    weather_desc = weather_data['current_condition'][0]['weatherDesc'][0]['value']

# Future Prediction
    if sleep_hours >= 7 and study_hours >= 5:
        future_prediction = "📈 High productivity expected."

    elif stress_level >= 8:
        future_prediction = "⚠️ Burnout risk detected."

    else:
        future_prediction = "📊 Moderate productivity expected."

# Wellness Status
    wellness_score = (
        sleep_hours * 10
        + study_hours * 5
        - stress_level * 7
    )

    if wellness_score > 80:
        wellness_status = "🌟 Excellent"

    elif wellness_score > 50:
        wellness_status = "👍 Stable"

    else:
        wellness_status = "⚠️ Needs Attention"

# Motivation Quote
    if emotion == "LABEL_0":
        quote = "Stay calm and trust yourself."

    elif emotion == "LABEL_1":
        quote = "Small progress is still progress."

    else:
        quote = "Use today's energy wisely."

# Recommendation
    if stress_level >= 8:
        recommendation = "Reduce study overload and rest properly."

    elif study_hours < 3:
        recommendation = "Increase study consistency gradually."

    else:
        recommendation = "Maintain your current momentum."

# AI Insight
    if stress_level >= 8 and sleep_hours < 5:
        ai_insight = "⚠️ Severe stress pattern detected."

    elif study_hours >= 6 and sleep_hours >= 7:
        ai_insight = "🚀 Excellent balance detected."

    else:
        ai_insight = "📊 Stable productivity pattern detected."

# Analytics Chart
    data = pd.DataFrame({
        "Category": ["Sleep", "Study", "Stress"],
        "Value": [sleep_hours, study_hours, stress_level]
    })

    fig = px.bar(
        data,
        x="Category",
        y="Value",
        title="MoodMind Analytics"
    )

# Save User History
    history = pd.DataFrame({
        "Name": [name],
        "Stress": [stress_level],
        "Sleep": [sleep_hours],
        "Study": [study_hours],
        "Emotion": [emotion]
    })

    history.to_csv(
        "moodmind_history.csv",
        mode="a",
        header=False,
        index=False
    )

# Final Report
    report = f"""

🧠 MoodMind AI Pro Report

🕒 Current Time:
{current_time}

👤 Name:
{name}

🌤️ Weather:
{temperature}°C, {weather_desc}

😊 Emotion:
{emotion}

📊 Confidence Score:
{score}%

⚡ Productivity Score:
{productivity}%

🔮 Future Prediction:
{future_prediction}

🧠 Wellness Status:
{wellness_status}

🧠 AI Insight:
{ai_insight}

😰 Stress Level:
{stress_level}/10

📅 Exam Countdown:
{exam_days} days

😴 Sleep Hours:
{sleep_hours}

📚 Study Hours:
{study_hours}

💡 Motivation:
{quote}

🚀 Recommendation:
{recommendation}
"""

# Generate PDF
    pdf = FPDF()

    pdf.add_page()

    pdf.set_font("Arial", size=12)

    clean_report = report.encode(
        "latin-1",
        "ignore"
    ).decode(
        "latin-1"
    )

    pdf.multi_cell(
        0,
        10,
        clean_report
    )

    pdf_file = "MoodMind_Report.pdf"

    pdf.output(pdf_file)

    return report, fig, pdf_file

# Interface

interface = gr.Interface(

    fn=moodmind_ai,

    inputs=[

        gr.Textbox(
            label="👤 Your Name"
        ),

        gr.Number(
            label="📅 Days Left For Exam"
        ),

        gr.Number(
            label="😴 Sleep Hours"
        ),

        gr.Number(
            label="📚 Study Hours Per Day"
        ),

        gr.Slider(
            minimum=1,
            maximum=10,
            label="😰 Stress Level"
        ),

        gr.Textbox(
            lines=6,
            label="🧠 How are you feeling?",
            placeholder="Describe your emotions, exams, goals..."
        )
    ],

    outputs=[

        gr.Textbox(
            lines=30,
            label="📋 AI Report"
        ),

        gr.Plot(
            label="📊 Analytics"
        ),

        gr.File(
            label="📄 Download PDF Report"
        )
    ],

    title="🧠 MoodMind AI Pro",

    description="Real-Time AI Productivity & Wellness Dashboard",

    theme="glass"

)

# Launch App

interface.launch()

from transformers import pipeline
import gradio as gr
from datetime import datetime
import requests
import pandas as pd
import plotly.express as px
from fpdf import FPDF
import sqlite3

# Establish SQLite connection (should be persistent across calls)
# Or consider moving this into the function if you want to create a new connection each time
# For simplicity and to avoid multiple connections/cursors, we'll connect once.
conn = sqlite3.connect("moodmind.db")
cursor = conn.cursor()

cursor.execute("""
CREATE TABLE IF NOT EXISTS users (
    name TEXT,
    stress INTEGER,
    sleep INTEGER,
    study INTEGER,
    emotion TEXT,
    career TEXT
)
""")
conn.commit()

# Load AI Model

emotion_classifier = pipeline(
    "text-classification",
    model="cardiffnlp/twitter-xlm-roberta-base-sentiment"
)

# Main Function

def moodmind_ai(
    name,
    exam_days,
    sleep_hours,
    study_hours,
    stress_level,
    career_goal,
    user_input
):
    # Current Time
    current_time = datetime.now().strftime("%d-%m-%Y %H:%M:%S")

    # Emotion Detection
    result = emotion_classifier(user_input)

    emotion = result[0]['label']
    score = round(result[0]['score'] * 100, 2)

    # Productivity
    productivity = 100 - int(stress_level * 5)

    # Weather
    city = "Nellore"

    weather_url = f"https://wttr.in/{city}?format=j1"

    weather_data = requests.get(weather_url).json()

    temperature = weather_data['current_condition'][0]['temp_C']

    weather_desc = weather_data['current_condition'][0]['weatherDesc'][0]['value']

    # Future Prediction
    if sleep_hours >= 7 and study_hours >= 5:
        future_prediction = "📈 High productivity expected."

    elif stress_level >= 8:
        future_prediction = "⚠️ Burnout risk detected."

    else:
        future_prediction = "📊 Moderate productivity expected."

    # Wellness Status
    wellness_score = (
        sleep_hours * 10
        + study_hours * 5
        - stress_level * 7
    )

    if wellness_score > 80:
        wellness_status = "🌟 Excellent"

    elif wellness_score > 50:
        wellness_status = "👍 Stable"

    else:
        wellness_status = "⚠️ Needs Attention"

    # Motivation Quote
    if emotion == "LABEL_0":
        quote = "Stay calm and trust yourself."

    elif emotion == "LABEL_1":
        quote = "Small progress is still progress."

    else:
        quote = "Use today's energy wisely."

    # Recommendation
    if stress_level >= 8:
        recommendation = "Reduce study overload and rest properly."

    elif study_hours < 3:
        recommendation = "Increase study consistency gradually."

    else:
        recommendation = "Maintain your current momentum."

    # AI Insight
    if stress_level >= 8 and sleep_hours < 5:
        ai_insight = "⚠️ Severe stress pattern detected."

    elif study_hours >= 6 and sleep_hours >= 7:
        ai_insight = "🚀 Excellent balance detected."

    else:
        ai_insight = "📊 Stable productivity pattern detected."

    # Career Roadmap
    if career_goal == "Software Engineer":

        roadmap = """

💻 Roadmap:

* Learn Python
* Learn DSA
* Build Projects
* Practice Interviews
  """

    elif career_goal == "AI Engineer":

        roadmap = """

🤖 Roadmap:

* Learn Python
* Machine Learning
* Deep Learning
* Build AI Projects
  """

    elif career_goal == "Government Job":

        roadmap = """

📘 Roadmap:

* Daily Current Affairs
* Mock Tests
* Time Management
  """

    elif career_goal == "Data Scientist":

        roadmap = """

📊 Roadmap:

* Learn Python
* Learn Data Analysis
* Learn Machine Learning
  """

    else:

        roadmap = """

🚀 Roadmap:

* Stay Consistent
* Build Skills
* Improve Communication
  """

    # Exam Prediction

    result_score = (
        study_hours * 10
        + sleep_hours * 5
        - stress_level * 4
    )

    if result_score >= 80:
        exam_prediction = "🏆 Excellent Result Expected"

    elif result_score >= 50:
        exam_prediction = "👍 Good Result Expected"

    else:
        exam_prediction = "⚠️ Improvement Needed"

    # AI Daily Routine

    routine = f"""
  🌅 Morning:
* Wake up at 6 AM
* Exercise 15 mins

📚 Study Session:

* {study_hours} focused hours

😴 Sleep:

* Sleep before 11 PM

🎯 Goal:

* Improve towards {career_goal}
  """

    # Achievement Score

    achievement_score = (
        productivity
        + study_hours * 5
        + sleep_hours * 3
    )

    achievement_score = int(achievement_score)

    # Rank System

    if achievement_score >= 120:
        rank = "👑 Legend"

    elif achievement_score >= 90:
        rank = "🔥 Advanced"

    elif achievement_score >= 60:
        rank = "🚀 Rising Star"

    else:
        rank = "🌱 Beginner"

    # Analytics Chart

    data = pd.DataFrame({
        "Category": [
            "Sleep",
            "Study",
            "Stress",
            "Productivity"
        ],

        "Value": [
            sleep_hours,
            study_hours,
            stress_level,
            productivity
        ]

    })

    fig = px.bar(
        data,
        x="Category",
        y="Value",
        title="MoodMind Analytics"
    )

    # Save User History to CSV

    history = pd.DataFrame({
        "Name": [name],
        "Stress": [stress_level],
        "Sleep": [sleep_hours],
        "Study": [study_hours],
        "Emotion": [emotion],
        "Career": [career_goal]
    })

    history.to_csv(
        "moodmind_history.csv",
        mode="a",
        header=False,
        index=False
    )

    # Save User History to SQLite
    cursor.execute("""
    INSERT INTO users VALUES (?, ?, ?, ?, ?, ?)
    """, (
        name,
        stress_level,
        sleep_hours,
        study_hours,
        emotion,
        career_goal
    ))
    conn.commit()

    # Final Report

    report = f"""
  🧠 MoodMind AI Pro MAX Report

🕒 Current Time:
{current_time}

👤 Name:
{name}

🌤️ Weather:
{temperature}°C, {weather_desc}

😊 Emotion:
{emotion}

📊 Confidence Score:
{score}%

⚡ Productivity Score:
{productivity}%

🔮 Future Prediction:
{future_prediction}

🧠 Wellness Status:
{wellness_status}

🧠 AI Insight:
{ai_insight}

🏅 AI Rank:
{rank}

⭐ Achievement Score:
{achievement_score}/150

🎯 Career Goal:
{career_goal}

🏆 Exam Prediction:
{exam_prediction}

😰 Stress Level:
{stress_level}/10

📅 Exam Countdown:
{exam_days} days

😴 Sleep Hours:
{sleep_hours}

📚 Study Hours:
{study_hours}

💡 Motivation:
{quote}

{roadmap}

{routine}

🚀 Recommendation:
{recommendation}
"""

    # Generate PDF
    pdf = FPDF()

    pdf.add_page()

    pdf.set_font("Arial", size=12)

    clean_report = report.encode(
        "latin-1",
        "ignore"
    ).decode(
        "latin-1"
    )

    pdf.multi_cell(
        0,
        10,
        clean_report
    )

    pdf_file = "MoodMind_Report.pdf"

    pdf.output(pdf_file)

    return report, fig, pdf_file

# Professional Multi-Tab UI

with gr.Blocks(theme=gr.themes.Glass()) as interface:

    gr.Markdown("# 🧠 MoodMind AI Pro MAX")

    with gr.Tab("📊 Dashboard"):

        name = gr.Textbox(
            label="👤 Your Name"
        )

        exam_days = gr.Number(
            label="📅 Days Left For Exam"
        )

        sleep_hours = gr.Number(
            label="😴 Sleep Hours"
        )

        study_hours = gr.Number(
            label="📚 Study Hours Per Day"
        )

        stress_level = gr.Slider(
            minimum=1,
            maximum=10,
            label="😰 Stress Level"
        )

        career_goal = gr.Dropdown(
            choices=[
                "Software Engineer",
                "AI Engineer",
                "Government Job",
                "Data Scientist",
                "Cyber Security",
                "Teacher"
            ],
            label="🎯 Career Goal"
        )

        user_input = gr.Textbox(
            lines=6,
            label="🧠 How are you feeling?",
            placeholder="Describe your emotions, exams, goals..."
        )

        submit = gr.Button("🚀 Analyze")

        report_output = gr.Textbox(
            lines=35,
            label="📋 AI Report"
        )

        chart_output = gr.Plot(
            label="📊 Analytics"
        )

        pdf_output = gr.File(
            label="📄 Download PDF Report"
        )

        submit.click(
            fn=moodmind_ai,

            inputs=[
                name,
                exam_days,
                sleep_hours,
                study_hours,
                stress_level,
                career_goal,
                user_input
            ],

            outputs=[
                report_output,
                chart_output,
                pdf_output
            ]
        )

# Launch App

interface.launch()

import sqlite3

conn = sqlite3.connect("moodmind.db")

cursor = conn.cursor()

cursor.execute("""
CREATE TABLE IF NOT EXISTS users (
    name TEXT,
    stress INTEGER,
    sleep INTEGER,
    study INTEGER,
    emotion TEXT,
    career TEXT
)
""")

conn.commit()

from transformers import pipeline
import gradio as gr
from datetime import datetime
import requests
import pandas as pd
import plotly.express as px
from fpdf import FPDF
import sqlite3

# =========================

# DATABASE SETUP

# =========================

conn = sqlite3.connect(
"moodmind.db",
check_same_thread=False
)

cursor = conn.cursor()

cursor.execute("""
CREATE TABLE IF NOT EXISTS users (
name TEXT,
stress INTEGER,
sleep INTEGER,
system_study INTEGER,
emotion TEXT,
career TEXT,
productivity INTEGER
)
""")

conn.commit()

# =========================

# LOAD AI MODEL

# =========================

emotion_classifier = pipeline(
"text-classification",
model="cardiffnlp/twitter-xlm-roberta-base-sentiment"
)

# =========================

# MAIN FUNCTION

# =========================

def moodmind_ai(
name,
exam_days,
sleep_hours,
study_hours,
stress_level,
career_goal,
user_input
):

    # Current Time
    current_time = datetime.now().strftime(
        "%d-%m-%Y %H:%M:%S"
    )

    # Emotion Detection
    result = emotion_classifier(user_input)

    emotion = result[0]["label"]

    score = round(
        result[0]["score"] * 100,
        2
    )

    # Productivity
    productivity = 100 - int(
        stress_level * 5
    )

    # Weather API
    city = "Nellore"

    weather_url = f"https://wttr.in/{city}?format=j1"

    weather_data = requests.get(
        weather_url
    ).json()

    temperature = weather_data[
        "current_condition"
    ][0]["temp_C"]

    weather_desc = weather_data[
        "current_condition"
    ][0]["weatherDesc"][0]["value"]

    # Future Prediction
    if sleep_hours >= 7 and study_hours >= 5:

        future_prediction = (
            "📈 High productivity expected."
        )

    elif stress_level >= 8:

        future_prediction = (
            "⚠️ Burnout risk detected."
        )

    else:

        future_prediction = (
            "📊 Moderate productivity expected."
        )

    # Wellness Score
    wellness_score = (
        sleep_hours * 10
        + study_hours * 5
        - stress_level * 7
    )

    if wellness_score > 80:

        wellness_status = "🌟 Excellent"

    elif wellness_score > 50:

        wellness_status = "👍 Stable"

    else:

        wellness_status = "⚠️ Needs Attention"

    # Motivation
    if emotion == "LABEL_0":

        quote = (
            "Stay calm and trust yourself."
        )

    elif emotion == "LABEL_1":

        quote = (
            "Small progress is still progress."
        )

    else:

        quote = (
            "Use today's energy wisely."
        )

    # Recommendation
    if stress_level >= 8:

        recommendation = (
            "Reduce study overload and rest properly."
        )

    elif study_hours < 3:

        recommendation = (
            "Increase study consistency gradually."
        )

    else:

        recommendation = (
            "Maintain your current momentum."
        )

    # AI Insight
    if (
        stress_level >= 8
        and sleep_hours < 5
    ):

        ai_insight = (
            "⚠️ Severe stress pattern detected."
        )

    elif (
        study_hours >= 6
        and sleep_hours >= 7
    ):

        ai_insight = (
            "🚀 Excellent balance detected."
        )

    else:

        ai_insight = (
            "📊 Stable productivity pattern detected."
        )

    # Career Roadmap
    if career_goal == "Software Engineer":

        roadmap = """

💻 Roadmap:

* Learn Python
* Learn DSA
* Build Projects
* Practice Interviews
  """

    elif career_goal == "AI Engineer":

        roadmap = """

🤖 Roadmap:

* Learn Python
* Machine Learning
* Deep Learning
* Build AI Projects
  """

    elif career_goal == "Government Job":

        roadmap = """

📘 Roadmap:

* Current Affairs
* Mock Tests
* Time Management
  """

    elif career_goal == "Data Scientist":

        roadmap = """

📊 Roadmap:

* Python
* Data Analysis
* Machine Learning
  """

    elif career_goal == "Cyber Security":

        roadmap = """

🛡️ Roadmap:

* Networking
* Linux
* Ethical Hacking
* Security Tools
  """

    else:

        roadmap = """

🚀 Roadmap:

* Stay Consistent
* Improve Communication
* Build Skills
  """

    # Exam Prediction

    result_score = (
    study_hours * 10
    + sleep_hours * 5
    - stress_level * 4
    )

    if result_score >= 80:

        exam_prediction = (
            "🏆 Excellent Result Expected"
        )

    elif result_score >= 50:

        exam_prediction = (
            "👍 Good Result Expected"
        )

    else:

        exam_prediction = (
            "⚠️ Improvement Needed"
        )

    # Daily Routine

    routine = f"""
  🌅 Morning:
* Wake up at 6 AM
* Exercise 15 mins

📚 Study Session:

* {study_hours} focused hours

😴 Sleep:

* Sleep before 11 PM

🎯 Goal:

* Improve towards {career_goal}
  """

    # Achievement Score

    achievement_score = int(
    productivity
    + study_hours * 5
    + sleep_hours * 3
    )

    # Rank

    if achievement_score >= 120:

        rank = "👑 Legend"

    elif achievement_score >= 90:

        rank = "🔥 Advanced"

    elif achievement_score >= 60:

        rank = "🚀 Rising Star"

    else:

        rank = "🌱 Beginner"

    # Save To Database

    cursor.execute(
    """
    INSERT INTO users VALUES (?, ?, ?, ?, ?, ?, ?)
    """,
    (
    name,
    stress_level,
    sleep_hours,
    study_hours,
    emotion,
    career_goal,
    productivity
    )
    )

    conn.commit()

    # Analytics Chart

    data = pd.DataFrame({
    "Category": [
    "Sleep",
    "Study",
    "Stress",
    "Productivity"
    ],

    "Value": [
        sleep_hours,
        study_hours,
        stress_level,
        productivity
    ]

    })

    fig = px.bar(
    data,
    x="Category",
    y="Value",
    title="MoodMind Analytics"
    )

    # Trend Analytics

    history_data = pd.read_sql_query(
    "SELECT * FROM users",
    conn
    )

    trend_fig = px.line(
    history_data,
    y="stress",
    title="Stress Trend Analysis"
    )

    # AI Coach

    if "stress" in user_input.lower():

        ai_coach = (
            "🧘 Try meditation and reduce overload."
        )

    elif "career" in user_input.lower():

        ai_coach = (
            "🚀 Build projects and improve consistency."
        )

    else:

        ai_coach = (
            "💡 Stay focused and improve daily."
        )

    # Final Report

    report = f"""
  🧠 MoodMind AI ULTRA Report

🕒 Current Time:
{current_time}

👤 Name:
{name}

🌤️ Weather:
{temperature}°C, {weather_desc}

😊 Emotion:
{emotion}

📊 Confidence Score:
{score}%

⚡ Productivity Score:
{productivity}%

🔮 Future Prediction:
{future_prediction}

🧠 Wellness Status:
{wellness_status}

🧠 AI Insight:
{ai_insight}

🏅 AI Rank:
{rank}

⭐ Achievement Score:
{achievement_score}/150

🎯 Career Goal:
{career_goal}

🏆 Exam Prediction:
{exam_prediction}

😰 Stress Level:
{stress_level}/10

📅 Exam Countdown:
{exam_days} days

😴 Sleep Hours:
{sleep_hours}

📚 Study Hours:
{study_hours}

💡 Motivation:
{quote}

🤖 AI Coach:
{ai_coach}

{roadmap}

{routine}

🚀 Recommendation:
{recommendation}
"""

    # Generate PDF
    pdf = FPDF()

    pdf.add_page()

    pdf.set_font(
        "Arial",
        size=12
    )

    clean_report = report.encode(
        "latin-1",
        "ignore"
    ).decode(
        "latin-1"
    )

    pdf.multi_cell(
        0,
        10,
        clean_report
    )

    pdf_file = "MoodMind_Report.pdf"

    pdf.output(pdf_file)

    return (
        report,
        fig,
        trend_fig,
        pdf_file
    )

# =========================

# PROFESSIONAL UI

# =========================

with gr.Blocks(
theme=gr.themes.Glass()
) as interface:

    gr.Markdown(
        "# 🧠 MoodMind AI ULTRA"
    )

    with gr.Tab("📊 Dashboard"):

        name = gr.Textbox(
            label="👤 Your Name"
        )

        exam_days = gr.Number(
            label="📅 Days Left For Exam"
        )

        sleep_hours = gr.Number(
            label="😴 Sleep Hours"
        )

        study_hours = gr.Number(
            label="📚 Study Hours"
        )

        stress_level = gr.Slider(
            minimum=1,
            maximum=10,
            label="😰 Stress Level"
        )

        career_goal = gr.Dropdown(
            choices=[
                "Software Engineer",
                "AI Engineer",
                "Government Job",
                "Data Scientist",
                "Cyber Security",
                "Teacher"
            ],
            label="🎯 Career Goal"
        )

        user_input = gr.Textbox(
            lines=6,
            label="🧠 How are you feeling?"
        )

        submit = gr.Button(
            "🚀 Analyze"
        )

        report_output = gr.Textbox(
            lines=35,
            label="📋 AI Report"
        )

        chart_output = gr.Plot(
            label="📊 Analytics"
        )

        trend_output = gr.Plot(
            label="📈 Stress Trends"
        )

        pdf_output = gr.File(
            label="📄 Download PDF Report"
        )

        submit.click(
            fn=moodmind_ai,

            inputs=[
                name,
                exam_days,
                sleep_hours,
                study_hours,
                stress_level,
                career_goal,
                user_input
            ],

            outputs=[
                report_output,
                chart_output,
                trend_output,
                pdf_output
            ]
        )

# =========================

# LAUNCH APP

# =========================

interface.launch()

# INSTALL REQUIRED LIBRARIES FIRST IN COLAB:

!pip install transformers gradio requests pandas plotly fpdf deepface tf-keras opencv-python

from transformers import pipeline
import gradio as gr
from datetime import datetime
import requests
import pandas as pd
import plotly.express as px
from fpdf import FPDF
import sqlite3
from deepface import DeepFace

# =========================================

# DATABASE SETUP

# =========================================

conn = sqlite3.connect(
"moodmind_ultra.db",
check_same_thread=False
)

cursor = conn.cursor()

cursor.execute("""
CREATE TABLE IF NOT EXISTS users (
name TEXT,
stress INTEGER,
sleep INTEGER,
study INTEGER,
emotion TEXT,
career TEXT,
productivity INTEGER
)
""")

conn.commit()

# =========================================

# LOAD NLP MODEL

# =========================================

emotion_classifier = pipeline(
"text-classification",
model="cardiffnlp/twitter-xlm-roberta-base-sentiment"
)

# =========================================

# MAIN AI FUNCTION

# =========================================

def moodmind_ai(
name,
exam_days,
sleep_hours,
study_hours,
stress_level,
career_goal,
user_input
):

# Current Time
    current_time = datetime.now().strftime(
    "%d-%m-%Y %H:%M:%S"
)

# Emotion Detection
    result = emotion_classifier(user_input)

    emotion = result[0]["label"]

    score = round(
    result[0]["score"] * 100,
    2
)

# Productivity
    productivity = 100 - int(
    stress_level * 5
)

# Weather API
    city = "Nellore"

    weather_url = f"https://wttr.in/{city}?format=j1"

    weather_data = requests.get(
    weather_url
).json()

    temperature = weather_data["current_condition"
][0]["temp_C"]

    weather_desc = weather_data["current_condition"
][0]["weatherDesc"][0]["value"]

# Future Prediction
    if sleep_hours >= 7 and study_hours >= 5:

        future_prediction = (
        "📈 High productivity expected."
)

    elif stress_level >= 8:

        future_prediction = (
        "⚠️ Burnout risk detected."
)

    else:

        future_prediction = (
        "📊 Moderate productivity expected."
)

# Wellness Score
    wellness_score = (
    sleep_hours * 10
    + study_hours * 5
    - stress_level * 7
)

    if wellness_score > 80:

        wellness_status = "🌟 Excellent"

    elif wellness_score > 50:

        wellness_status = "👍 Stable"

    else:

        wellness_status = "⚠️ Needs Attention"

# Motivation
    if emotion == "LABEL_0":

        quote = (
        "Stay calm and trust yourself."
)

    elif emotion == "LABEL_1":

        quote = (
        "Small progress is still progress."
)

    else:

        quote = (
        "Use today's energy wisely."
)

# Recommendation
    if stress_level >= 8:

        recommendation = (
        "Reduce study overload and rest properly."
)

    elif study_hours < 3:

        recommendation = (
        "Increase study consistency gradually."
)

    else:

        recommendation = (
        "Maintain your current momentum."
)

# AI Insight
    if (
    stress_level >= 8
    and sleep_hours < 5
):

        ai_insight = (
        "⚠️ Severe stress pattern detected."
)

    elif (
    study_hours >= 6
    and sleep_hours >= 7
):

        ai_insight = (
        "🚀 Excellent balance detected."
)

    else:

        ai_insight = (
        "📊 Stable productivity pattern detected."
)

# Career Roadmap
    if career_goal == "Software Engineer":

        roadmap = """

💻 Roadmap:

* Learn Python
* Learn DSA
* Build Projects
* Practice Interviews
  """

    elif career_goal == "AI Engineer":

        roadmap = """

🤖 Roadmap:

* Learn Python
* Machine Learning
* Deep Learning
* Build AI Projects
  """

    elif career_goal == "Government Job":

        roadmap = """

📘 Roadmap:

* Current Affairs
* Mock Tests
* Time Management
  """

    elif career_goal == "Data Scientist":

        roadmap = """

📊 Roadmap:

* Python
* Data Analysis
* Machine Learning
  """

    elif career_goal == "Cyber Security":

        roadmap = """

🛡️ Roadmap:

* Networking
* Linux
* Ethical Hacking
  """

    else:

        roadmap = """

🚀 Roadmap:

* Stay Consistent
* Improve Communication
* Build Skills
  """

# Exam Prediction

    result_score = (
    study_hours * 10
    + sleep_hours * 5
    - stress_level * 4
)

    if result_score >= 80:

        exam_prediction = (
        "🏆 Excellent Result Expected"
)

    elif result_score >= 50:

        exam_prediction = (
        "👍 Good Result Expected"
)

    else:

        exam_prediction = (
        "⚠️ Improvement Needed"
)

# Daily Routine

    routine = f"""
  🌅 Morning:
* Wake up at 6 AM
* Exercise 15 mins

📚 Study Session:

* {study_hours} focused hours

😴 Sleep:

* Sleep before 11 PM

🎯 Goal:

* Improve towards {career_goal}
  """

# Achievement Score

    achievement_score = int(
    productivity
    + study_hours * 5
    + sleep_hours * 3
)

# Rank

    if achievement_score >= 120:

        rank = "👑 Legend"

    elif achievement_score >= 90:

        rank = "🔥 Advanced"

    elif achievement_score >= 60:

        rank = "🚀 Rising Star"

    else:

        rank = "🌱 Beginner"

# Save Data

    cursor.execute(
    """
  INSERT INTO users VALUES (?, ?, ?, ?, ?, ?, ?)
  """,
    (
    name,
    stress_level,
    sleep_hours,
    study_hours,
    emotion,
    career_goal,
    productivity
)
)

    conn.commit()

# Analytics Chart

    data = pd.DataFrame({
    "Category": [
    "Sleep",
    "Study",
    "Stress",
    "Productivity"
],

    "Value": [
        sleep_hours,
        study_hours,
        stress_level,
        productivity
    ]

})

    fig = px.bar(
    data,
    x="Category",
    y="Value",
    title="MoodMind Analytics"
)

# Trend Analytics

    history_data = pd.read_sql_query(
    "SELECT * FROM users",
    conn
)

    trend_fig = px.line(
    history_data,
    y="stress",
    title="Stress Trend Analysis"
)

# AI Coach

    if "stress" in user_input.lower():

        ai_coach = (
        "🧘 Try meditation and reduce overload."
)

    elif "career" in user_input.lower():

        ai_coach = (
        "🚀 Build projects and improve consistency."
)

    else:

        ai_coach = (
        "💡 Stay focused and improve daily."
)

# Final Report

    report = f"""
  🧠 MoodMind AI ULTRA X Report

🕒 Current Time:
{current_time}

👤 Name:
{name}

🌤️ Weather:
{temperature}°C, {weather_desc}

😊 Emotion:
{emotion}

📊 Confidence Score:
{score}%

⚡ Productivity Score:
{productivity}%

🔮 Future Prediction:
{future_prediction}

🧠 Wellness Status:
{wellness_status}

🧠 AI Insight:
{ai_insight}

🏅 AI Rank:
{rank}

⭐ Achievement Score:
{achievement_score}/150

🎯 Career Goal:
{career_goal}

🏆 Exam Prediction:
{exam_prediction}

😰 Stress Level:
{stress_level}/10

📅 Exam Countdown:
{exam_days} days

😴 Sleep Hours:
{sleep_hours}

📚 Study Hours:
{study_hours}

💡 Motivation:
{quote}

🤖 AI Coach:
{ai_coach}

{roadmap}

{routine}

🚀 Recommendation:
{recommendation}
"""

# Generate PDF
    pdf = FPDF()

    pdf.add_page()

    pdf.set_font(
    "Arial",
    size=12
)

    clean_report = report.encode(
    "latin-1",
    "ignore"
).decode(
    "latin-1"
)

    pdf.multi_cell(
    0,
    10,
    clean_report
)

    pdf_file = "MoodMind_Report.pdf"

    pdf.output(pdf_file)

    return (
    report,
    fig,
    trend_fig,
    pdf_file
)

# =========================================

# FACE EMOTION DETECTION

# =========================================

def detect_face_emotion(image):

    result = DeepFace.analyze(
    image,
    actions=["emotion"],
    enforce_detection=False
)

    emotion = result[0]["dominant_emotion"]

    return f"😎 Detected Face Emotion: {emotion}"

# =========================================

# UI

# =========================================

with gr.Blocks(
theme=gr.themes.Glass()
) as interface:

    gr.Markdown(
    "# 🧠 MoodMind AI ULTRA X"
)

# DASHBOARD TAB
    with gr.Tab("📊 Dashboard"):

        name = gr.Textbox(
        label="👤 Your Name"
)

        exam_days = gr.Number(
        label="📅 Days Left For Exam"
)

        sleep_hours = gr.Number(
        label="😴 Sleep Hours"
)

        study_hours = gr.Number(
        label="📚 Study Hours"
)

        stress_level = gr.Slider(
        minimum=1,
        maximum=10,
        label="😰 Stress Level"
)

        career_goal = gr.Dropdown(
        choices=[
            "Software Engineer",
            "AI Engineer",
            "Government Job",
            "Data Scientist",
            "Cyber Security",
            "Teacher"
        ],
        label="🎯 Career Goal"
)

        user_input = gr.Textbox(
        lines=6,
        label="🧠 How are you feeling?"
)

        submit = gr.Button(
        "🚀 Analyze"
)

        report_output = gr.Textbox(
        lines=35,
        label="📋 AI Report"
)

        chart_output = gr.Plot(
        label="📊 Analytics"
)

        trend_output = gr.Plot(
        label="📈 Stress Trends"
)

        pdf_output = gr.File(
        label="📄 Download PDF Report"
)

        submit.click(
        fn=moodmind_ai,

        inputs=[
            name,
            exam_days,
            sleep_hours,
            study_hours,
            stress_level,
            career_goal,
            user_input
        ],

        outputs=[
            report_output,
            chart_output,
            trend_output,
            pdf_output
        ]
)

# FACE EMOTION TAB
    with gr.Tab("😎 Face Emotion AI"):

        image_input = gr.Image(
        type="filepath",
        label="📸 Upload Face Image"
)

        image_button = gr.Button(
        "😎 Analyze Face Emotion"
)

        image_output = gr.Textbox(
        label="🧠 Face Emotion Result"
)

        image_button.click(
        fn=detect_face_emotion,
        inputs=image_input,
        outputs=image_output
)

# =========================================

# LAUNCH APP

# =========================================

interface.launch()

# =========================================

# INSTALL THESE FIRST IN GOOGLE COLAB

# =========================================

!pip install transformers

!pip install gradio

!pip install requests

!pip install pandas

!pip install plotly

!pip install fpdf

!pip install deepface

!pip install tf-keras

!pip install opencv-python

!pip install SpeechRecognition

!pip install pyttsx3

!pip install PyPDF2

# =========================================

# IMPORTS

# =========================================

from transformers import pipeline
import gradio as gr
from datetime import datetime
import requests
import pandas as pd
import plotly.express as px
from fpdf import FPDF
import sqlite3
from deepface import DeepFace
import speech_recognition as sr
from PyPDF2 import PdfReader

# =========================================

# DATABASE

# =========================================

conn = sqlite3.connect(
    "moodmind_omega.db",
    check_same_thread=False
)

cursor = conn.cursor()

cursor.execute("""
CREATE TABLE IF NOT EXISTS users (
    name TEXT,
    stress INTEGER,
    sleep INTEGER,
    study INTEGER,
    emotion TEXT,
    career TEXT,
    productivity INTEGER
)
""")

cursor.execute("""
CREATE TABLE IF NOT EXISTS accounts (
    username TEXT,
    password TEXT
)
""")

conn.commit()

# =========================================

# LOAD AI MODEL

# =========================================

emotion_classifier = pipeline(
    "text-classification",
    model="cardiffnlp/twitter-xlm-roberta-base-sentiment"
)

# =========================================

# REGISTER FUNCTION

# =========================================

def register(username, password):
    cursor.execute(
        "INSERT INTO accounts VALUES (?, ?)",
        (username, password)
    )

    conn.commit()

    return "✅ Account Created Successfully"

# =========================================

# VOICE ASSISTANT

# =========================================

def voice_assistant():
    recognizer = sr.Recognizer()

    return "🎤 Voice Assistant Ready"

# =========================================

# AI CHATBOT

# =========================================

def ai_chatbot(user_question):
    question = user_question.lower()

    if "career" in question:

        return """
🚀 Career Advice:

* Build Projects
* Improve Coding
* Stay Consistent
  """

    elif "stress" in question:

        return """
🧘 Stress Advice:

* Sleep Properly
* Take Breaks
* Exercise Daily
  """

    elif "study" in question:

        return """
📚 Study Advice:

* Use Pomodoro Technique
* Revise Daily
* Practice Mock Tests
  """

    else:

        return """
💡 AI Coach:
Stay focused and improve daily.
"""

# =========================================

# TIMETABLE GENERATOR

# =========================================

def generate_timetable(study_hours):
    timetable = f"""
📅 AI Smart Timetable

🌅 6:00 AM - Wake Up
🏃 7:00 AM - Exercise
📚 9:00 AM - Study Session
🍱 1:00 PM - Lunch Break
📖 3:00 PM - Revision
🧘 6:00 PM - Relaxation
😴 10:00 PM - Sleep

📚 Total Study Hours:
{study_hours}
"""

    return timetable

# =========================================

# RESUME ANALYZER

# =========================================

def analyze_resume(file):
    reader = PdfReader(file.name)

    text = ""

    for page in reader.pages:

        extracted = page.extract_text()

        if extracted:
            text += extracted

    skills = []

    if "Python" in text:
        skills.append("Python")

    if "Machine Learning" in text:
        skills.append("Machine Learning")

    if "SQL" in text:
        skills.append("SQL")

    if "AI" in text:
        skills.append("Artificial Intelligence")

    if len(skills) == 0:

        return """
⚠️ No major technical skills detected.
Add more technical keywords.
"""

    return f"""
✅ Resume Analysis Completed

🔥 Skills Detected:
{', '.join(skills)}

🚀 Resume looks technically strong.
"""

# =========================================

# FACE EMOTION AI

# =========================================

def detect_face_emotion(image):
    result = DeepFace.analyze(
        image,
        actions=["emotion"],
        enforce_detection=False
    )

    emotion = result[0]["dominant_emotion"]

    return f"😎 Face Emotion Detected: {emotion}"

# =========================================

# MAIN AI SYSTEM

# =========================================

def moodmind_ai(
    name,
    exam_days,
    sleep_hours,
    study_hours,
    stress_level,
    career_goal,
    user_input
):
    current_time = datetime.now().strftime(
        "%d-%m-%Y %H:%M:%S"
    )

    # NLP Emotion
    result = emotion_classifier(user_input)

    emotion = result[0]["label"]

    score = round(
        result[0]["score"] * 100,
        2
    )

    # Productivity
    productivity = 100 - int(
        stress_level * 5
    )

    # Weather API
    city = "Nellore"

    weather_url = f"https://wttr.in/{city}?format=j1"

    weather_data = requests.get(
        weather_url
    ).json()

    temperature = weather_data[
        "current_condition"
    ][0]["temp_C"]

    weather_desc = weather_data[
        "current_condition"
    ][0]["weatherDesc"][0]["value"]

    # Future Prediction
    if sleep_hours >= 7 and study_hours >= 5:

        future_prediction = (
            "📈 High productivity expected."
        )

    elif stress_level >= 8:

        future_prediction = (
            "⚠️ Burnout risk detected."
        )

    else:

        future_prediction = (
            "📊 Moderate productivity expected."
        )

    # Wellness Score
    wellness_score = (
        sleep_hours * 10
        + study_hours * 5
        - stress_level * 7
    )

    if wellness_score > 80:

        wellness_status = "🌟 Excellent"

    elif wellness_score > 50:

        wellness_status = "👍 Stable"

    else:

        wellness_status = "⚠️ Needs Attention"

    # Recommendation
    if stress_level >= 8:

        recommendation = (
            "Reduce overload and rest properly."
        )

    elif study_hours < 3:

        recommendation = (
            "Increase study consistency."
        )

    else:

        recommendation = (
            "Maintain current momentum."
        )

    # Career Roadmap
    if career_goal == "Software Engineer":

        roadmap = """
💻 Software Engineer Roadmap:

* Python
* DSA
* Projects
* Interviews
  """

    elif career_goal == "AI Engineer":

        roadmap = """
🤖 AI Engineer Roadmap:

* Python
* ML
* Deep Learning
* AI Projects
  """

    elif career_goal == "Government Job":

        roadmap = """
📘 Government Job Roadmap:

* Current Affairs
* Mock Tests
* Revision
  """

    else:

        roadmap = """
🚀 Stay consistent and improve daily.
"""

    # Achievement Score
    achievement_score = int(
        productivity
        + study_hours * 5
        + sleep_hours * 3
    )

    # Rank
    if achievement_score >= 120:

        rank = "👑 Legend"

    elif achievement_score >= 90:

        rank = "🔥 Advanced"

    elif achievement_score >= 60:

        rank = "🚀 Rising Star"

    else:

        rank = "🌱 Beginner"

    # Save Database
    cursor.execute(
        """
        INSERT INTO users VALUES (?, ?, ?, ?, ?, ?, ?)
        """,
        (
            name,
            stress_level,
            sleep_hours,
            study_hours,
            emotion,
            career_goal,
            productivity
        )
    )

    conn.commit()

    # Analytics
    data = pd.DataFrame({
        "Category": [
            "Sleep",
            "Study",
            "Stress",
            "Productivity"
        ],

        "Value": [
            sleep_hours,
            study_hours,
            stress_level,
            productivity
        ]
    })

    fig = px.bar(
        data,
        x="Category",
        y="Value",
        title="MoodMind Analytics"
    )

    # Trend Analytics
    history_data = pd.read_sql_query(
        "SELECT * FROM users",
        conn
    )

    trend_fig = px.line(
        history_data,
        y="stress",
        title="Stress Trend Analysis"
    )

    # Leaderboard
    leaderboard = pd.read_sql_query(
        """
        SELECT name, productivity
        FROM users
        ORDER BY productivity DESC
        LIMIT 5
        """,
        conn
    )

    leaderboard_text = leaderboard.to_string(
        index=False
    )

    # Final Report
    report = f"""
🧠 MoodMind AI OMEGA Report

🕒 Current Time:
{current_time}

👤 Name:
{name}

🌤️ Weather:
{temperature}°C, {weather_desc}

😊 Emotion:
{emotion}

📊 Confidence Score:
{score}%

⚡ Productivity:
{productivity}%

🏅 Rank:
{rank}

⭐ Achievement Score:
{achievement_score}/150

🧠 Wellness:
{wellness_status}

🔮 Future Prediction:
{future_prediction}

🎯 Career Goal:
{career_goal}

😰 Stress Level:
{stress_level}/10

📅 Exam Countdown:
{exam_days} days

😴 Sleep Hours:
{sleep_hours}

📚 Study Hours:
{study_hours}

{roadmap}

🚀 Recommendation:
{recommendation}

🏆 Leaderboard:
{leaderboard_text}
"""

    # Generate PDF
    pdf = FPDF()

    pdf.add_page()

    pdf.set_font(
        "Arial",
        size=12
    )

    clean_report = report.encode(
        "latin-1",
        "ignore"
    ).decode(
        "latin-1"
    )

    pdf.multi_cell(
        0,
        10,
        clean_report
    )

    pdf_file = "MoodMind_OMEGA_Report.pdf"

    pdf.output(pdf_file)

    return (
        report,
        fig,
        trend_fig,
        pdf_file
    )

# =========================================

# UI

# =========================================

with gr.Blocks(
    theme=gr.themes.Glass()
) as interface:
    gr.Markdown(
        "# 🧠 MoodMind AI OMEGA"
    )

    # MAIN DASHBOARD
    with gr.Tab("📊 Dashboard"):

        name = gr.Textbox(
            label="👤 Your Name"
        )

        exam_days = gr.Number(
            label="📅 Exam Days Left"
        )

        sleep_hours = gr.Number(
            label="😴 Sleep Hours"
        )

        study_hours = gr.Number(
            label="📚 Study Hours"
        )

        stress_level = gr.Slider(
            minimum=1,
            maximum=10,
            label="😰 Stress Level"
        )

        career_goal = gr.Dropdown(
            choices=[
                "Software Engineer",
                "AI Engineer",
                "Government Job",
                "Data Scientist"
            ],
            label="🎯 Career Goal"
        )

        user_input = gr.Textbox(
            lines=6,
            label="🧠 How are you feeling?"
        )

        submit = gr.Button(
            "🚀 Analyze"
        )

        report_output = gr.Textbox(
            lines=35,
            label="📋 AI Report"
        )

        chart_output = gr.Plot(
            label="📊 Analytics"
        )

        trend_output = gr.Plot(
            label="📈 Trends"
        )

        pdf_output = gr.File(
            label="📄 Download PDF"
        )

        submit.click(
            fn=moodmind_ai,

            inputs=[
                name,
                exam_days,
                sleep_hours,
                study_hours,
                stress_level,
                career_goal,
                user_input
            ],

            outputs=[
                report_output,
                chart_output,
                trend_output,
                pdf_output
            ]
        )

    # FACE EMOTION TAB
    with gr.Tab("😎 Face Emotion AI"):

        image_input = gr.Image(
            type="filepath",
            label="📸 Upload Face Image"
        )

        image_button = gr.Button(
            "😎 Analyze Emotion"
        )

        image_output = gr.Textbox(
            label="🧠 Face Emotion Result"
        )

        image_button.click(
            fn=detect_face_emotion,
            inputs=image_input,
            outputs=image_output
        )

    # AI CHATBOT TAB
    with gr.Tab("🤖 AI Coach"):

        chatbot_input = gr.Textbox(
            lines=5,
            label="Ask AI Coach"
        )

        chatbot_button = gr.Button(
            "🤖 Ask"
        )

        chatbot_output = gr.Textbox(
            lines=10,
            label="AI Coach Response"
        )

        chatbot_button.click(
            fn=ai_chatbot,
            inputs=chatbot_input,
            outputs=chatbot_output
        )

    # TIMETABLE TAB
    with gr.Tab("📅 Timetable Generator"):

        timetable_hours = gr.Number(
            label="📚 Study Hours"
        )

        timetable_button = gr.Button(
            "📅 Generate Timetable"
        )

        timetable_output = gr.Textbox(
            lines=15,
            label="📅 AI Timetable"
        )

        timetable_button.click(
            fn=generate_timetable,
            inputs=timetable_hours,
            outputs=timetable_output
        )

    # RESUME ANALYZER TAB
    with gr.Tab("📄 Resume Analyzer"):

        resume_input = gr.File(
            label="📄 Upload Resume PDF"
        )

        resume_button = gr.Button(
            "📄 Analyze Resume"
        )

        resume_output = gr.Textbox(
            lines=15,
            label="📋 Resume Analysis"
        )

        resume_button.click(
            fn=analyze_resume,
            inputs=resume_input,
            outputs=resume_output
        )

    # LOGIN TAB
    with gr.Tab("🔐 Register"):

        username = gr.Textbox(
            label="👤 Username"
        )

        password = gr.Textbox(
            label="🔑 Password",
            type="password"
        )

        register_button = gr.Button(
            "✅ Register"
        )

        register_output = gr.Textbox(
            label="📋 Status"
        )

        register_button.click(
            fn=register,
            inputs=[
                username,
                password
            ],
            outputs=register_output
        )

    # VOICE ASSISTANT TAB
    with gr.Tab("🎤 Voice Assistant"):

        voice_button = gr.Button(
            "🎤 Start Voice Assistant"
        )

        voice_output = gr.Textbox(
            lines=5,
            label="🎤 Voice Assistant"
        )

        voice_button.click(
            fn=voice_assistant,
            outputs=voice_output
        )

# =========================================

# LAUNCH APP

# =========================================

interface.launch()

# =========================================================

# INSTALL THESE IN GOOGLE COLAB FIRST

# =========================================================

# !pip install transformers

# !pip install gradio

# !pip install requests

# !pip install pandas

# !pip install plotly

# !pip install fpdf

# !pip install deepface

# !pip install tf-keras

# !pip install opencv-python

# !pip install SpeechRecognition

# !pip install PyPDF2

# =========================================================

# IMPORTS

# =========================================================

from transformers import pipeline
import gradio as gr
from datetime import datetime
import requests
import pandas as pd
import plotly.express as px
from fpdf import FPDF
import sqlite3
from deepface import DeepFace
import speech_recognition as sr
from PyPDF2 import PdfReader
import random

# =========================================================

# DATABASE

# =========================================================

conn = sqlite3.connect(
"moodmind_ultimate.db",
check_same_thread=False
)

cursor = conn.cursor()

cursor.execute("""
CREATE TABLE IF NOT EXISTS users (
name TEXT,
city TEXT,
stress INTEGER,
sleep INTEGER,
study INTEGER,
emotion TEXT,
career TEXT,
productivity INTEGER
)
""")

cursor.execute("""
CREATE TABLE IF NOT EXISTS accounts (
username TEXT,
password TEXT
)
""")

conn.commit()

# =========================================================

# LOAD NLP MODEL

# =========================================================

emotion_classifier = pipeline(
"text-classification",
model="cardiffnlp/twitter-xlm-roberta-base-sentiment"
)

# =========================================================

# RANDOM MOTIVATION

# =========================================================

quotes = [
"🌱 Small progress is still progress.",

"🚀 Discipline creates success.",

"🔥 Consistency beats motivation.",

"💡 Focus on improvement every day.",

"🏆 Success is built daily."

]

# =========================================================

# REGISTER

# =========================================================

def register(username, password):

    cursor.execute(
    "INSERT INTO accounts VALUES (?, ?)",
    (username, password)
)

    conn.commit()

    return "✅ Account Created Successfully"

# =========================================================

# VOICE ASSISTANT

# =========================================================

def voice_assistant():

    recognizer = sr.Recognizer()

    return """
🎤 Voice Assistant Ready

(Voice recognition works better locally
than in Google Colab.)
"""

# =========================================================

# AI CHATBOT

# =========================================================

def ai_chatbot(user_question):

    question = user_question.lower()

    if "career" in question:

        return """
🚀 Career Advice

• Build Projects
• Improve Coding
• Stay Consistent
• Practice Communication
"""

    elif "stress" in question:

        return """
🧘 Stress Advice

• Sleep Properly
• Exercise Daily
• Take Small Breaks
"""

    elif "study" in question:

        return """
📚 Study Advice

• Use Pomodoro Technique
• Revise Daily
• Practice Mock Tests
"""

    else:

        return """
💡 AI Coach

Stay focused and improve daily.
"""

# =========================================================

# TIMETABLE GENERATOR

# =========================================================

def generate_timetable(study_hours):

    timetable = f"""
📅 AI Smart Timetable

🌅 6:00 AM - Wake Up
🏃 7:00 AM - Exercise
📚 9:00 AM - Study Session
🍱 1:00 PM - Lunch Break
📖 3:00 PM - Revision
🧘 6:00 PM - Relaxation
😴 10:00 PM - Sleep

📚 Total Study Hours:
{study_hours}
"""

    return timetable

# =========================================================

# RESUME ANALYZER

# =========================================================

def analyze_resume(file):

    reader = PdfReader(file.name)

    text = ""

    for page in reader.pages:

        extracted = page.extract_text()

        if extracted:
            text += extracted

    skills = []

    if "Python" in text:
        skills.append("Python")

    if "Machine Learning" in text:
        skills.append("Machine Learning")

    if "SQL" in text:
        skills.append("SQL")

    if "AI" in text:
        skills.append("Artificial Intelligence")

    if "Java" in text:
        skills.append("Java")

    if len(skills) == 0:

        return """
⚠️ No major technical skills detected.
Add more technical keywords.
"""

    return f"""
✅ Resume Analysis Completed

🔥 Skills Detected:
{", ".join(skills)}

🚀 Resume looks technically strong.
"""

# =========================================================

# FACE EMOTION DETECTION

# =========================================================

def detect_face_emotion(image):

    result = DeepFace.analyze(
    image,
    actions=["emotion"],
    enforce_detection=False
)

    emotion = result[0]["dominant_emotion"]

    return f"😎 Face Emotion Detected: {emotion}"

# =========================================================

# MAIN AI SYSTEM

# =========================================================

def moodmind_ai(
name,
city,
exam_days,
sleep_hours,
study_hours,
stress_level,
career_goal,
user_input
):

    # Current Time
    current_time = datetime.now().strftime(
    "%d-%m-%Y %H:%M:%S"
)

    # NLP Emotion Detection
    result = emotion_classifier(user_input)

    emotion = result[0]["label"]

    score = round(
    result[0]["score"] * 100,
    2
)

    # Productivity
    productivity = 100 - int(
    stress_level * 5
)

    # Dynamic Weather
    weather_url = f"https://wttr.in/{city}?format=j1"

    weather_data = requests.get(
    weather_url
).json()

    temperature = weather_data[
    "current_condition"
][0]["temp_C"]

    weather_desc = weather_data[
    "current_condition"
][0]["weatherDesc"][0]["value"]

    # Dynamic Motivation
    quote = random.choice(quotes)

    # Future Prediction
    if sleep_hours >= 7 and study_hours >= 5:

        future_prediction = (
        "📈 High productivity expected."
)

    elif stress_level >= 8:

        future_prediction = (
        "⚠️ Burnout risk detected."
)

    else:

        future_prediction = (
        "📊 Moderate productivity expected."
)

    # Wellness
    wellness_score = (
    sleep_hours * 10
    + study_hours * 5
    - stress_level * 7
)

    if wellness_score > 80:

        wellness_status = "🌟 Excellent"

    elif wellness_score > 50:

        wellness_status = "👍 Stable"

    else:

        wellness_status = "⚠️ Needs Attention"

    # Recommendation
    if stress_level >= 8:

        recommendation = (
        "Reduce overload and rest properly."
)

    elif study_hours < 3:

        recommendation = (
        "Increase study consistency."
)

    else:

        recommendation = (
        "Maintain current momentum."
)

    # Career Roadmap
    if career_goal == "Software Engineer":

        roadmap = """

💻 Software Engineer Roadmap
• Python
• DSA
• Build Projects
• Interview Preparation
"""

    elif career_goal == "AI Engineer":

        roadmap = """

🤖 AI Engineer Roadmap
• Python
• Machine Learning
• Deep Learning
• AI Projects
"""

    elif career_goal == "Government Job":

        roadmap = """

📘 Government Job Roadmap
• Current Affairs
• Mock Tests
• Daily Revision
"""

    else:

        roadmap = """

🚀 Stay consistent and improve daily.
"""

    # Achievement Score
    achievement_score = int(
    productivity
    + study_hours * 5
    + sleep_hours * 3
)

    # Rank System
    if achievement_score >= 120:

        rank = "👑 Legend"

    elif achievement_score >= 90:

        rank = "🔥 Advanced"

    elif achievement_score >= 60:

        rank = "🚀 Rising Star"

    else:

        rank = "🌱 Beginner"

    # Save User Data
    cursor.execute(
    """
    INSERT INTO users VALUES (?, ?, ?, ?, ?, ?, ?, ?)
    """,
    (
        name,
        city,
        stress_level,
        sleep_hours,
        study_hours,
        emotion,
        career_goal,
        productivity
    )
)

    conn.commit()

    # Analytics Chart
    data = pd.DataFrame({

    "Category": [
        "Sleep",
        "Study",
        "Stress",
        "Productivity"
    ],

    "Value": [
        sleep_hours,
        study_hours,
        stress_level,
        productivity
    ]
})

    fig = px.bar(
    data,
    x="Category",
    y="Value",
    title="MoodMind Real-Time Analytics"
)

    # Dynamic Trend Graph
    history_data = pd.read_sql_query(
    "SELECT * FROM users",
    conn
)

    trend_fig = px.line(
    history_data,
    x=history_data.index,
    y="productivity",
    color="name",
    title="Real-Time Productivity Trends"
)

    # Dynamic Leaderboard
    leaderboard = pd.read_sql_query(
    """
    SELECT name,
    AVG(productivity) as score
    FROM users
    GROUP BY name
    ORDER BY score DESC
    LIMIT 10
    """,
    conn
)

    leaderboard_text = leaderboard.to_string(
    index=False
)

    # Final Report
    report = f"""

🧠 MoodMind AI ULTIMATE Report

🕒 Current Time:
{current_time}

👤 Name:
{name}

🌍 City:
{city}

🌤️ Weather:
{temperature}°C, {weather_desc}

😊 Emotion:
{emotion}

📊 Confidence Score:
{score}%

⚡ Productivity:
{productivity}%

🏅 Rank:
{rank}

⭐ Achievement Score:
{achievement_score}/150

🧠 Wellness:
{wellness_status}

🔮 Future Prediction:
{future_prediction}

🎯 Career Goal:
{career_goal}

😰 Stress Level:
{stress_level}/10

📅 Exam Countdown:
{exam_days} days

😴 Sleep Hours:
{sleep_hours}

📚 Study Hours:
{study_hours}

💡 Motivation:
{quote}

{roadmap}

🚀 Recommendation:
{recommendation}

🏆 Real-Time Leaderboard:
{leaderboard_text}
"""

    # PDF Report
    pdf = FPDF()

    pdf.add_page()

    pdf.set_font(
    "Arial",
    size=12
)

    clean_report = report.encode(
    "latin-1",
    "ignore"
).decode(
    "latin-1"
)

    pdf.multi_cell(
    0,
    10,
    clean_report
)

    pdf_file = "MoodMind_Ultimate_Report.pdf"

    pdf.output(pdf_file)

    return (
    report,
    fig,
    trend_fig,
    pdf_file
)

# =========================================================

# PEACEFUL UI

# =========================================================

css = """

body {

    background: linear-gradient(
    to right,
    #dfe9f3,
    #ffffff
);

}

.gradio-container {

    background-color: rgba(
    255,
    255,
    255,
    0.85
);

    border-radius: 20px;

}
"""

# =========================================================

# UI

# =========================================================

with gr.Blocks(

    theme=gr.themes.Soft(),
    css=css

) as interface:

    gr.Markdown(
    "# 🧠 MoodMind AI ULTIMATE"
)

    # DASHBOARD
    with gr.Tab("📊 Dashboard"):

        name = gr.Textbox(
        label="👤 Your Name"
)

        city = gr.Textbox(
        label="🌍 Your City"
)

        exam_days = gr.Number(
        label="📅 Exam Days Left"
)

        sleep_hours = gr.Number(
        label="😴 Sleep Hours"
)

        study_hours = gr.Number(
        label="📚 Study Hours"
)

        stress_level = gr.Slider(
        minimum=1,
        maximum=10,
        label="😰 Stress Level"
)

        career_goal = gr.Dropdown(
        choices=[
            "Software Engineer",
            "AI Engineer",
            "Government Job",
            "Data Scientist"
        ],
        label="🎯 Career Goal"
)

        user_input = gr.Textbox(
        lines=6,
        label="🧠 How are you feeling?"
)

        submit = gr.Button(
        "🚀 Analyze"
)

        report_output = gr.Textbox(
        lines=35,
        label="📋 AI Report"
)

        chart_output = gr.Plot(
        label="📊 Analytics"
)

        trend_output = gr.Plot(
        label="📈 Real-Time Trends"
)

        pdf_output = gr.File(
        label="📄 Download PDF"
)

        submit.click(

        fn=moodmind_ai,

        inputs=[
            name,
            city,
            exam_days,
            sleep_hours,
            study_hours,
            stress_level,
            career_goal,
            user_input
        ],

        outputs=[
            report_output,
            chart_output,
            trend_output,
            pdf_output
        ]
)

    # FACE AI
    with gr.Tab("😎 Face Emotion AI"):

        image_input = gr.Image(
        type="filepath",
        label="📸 Upload Face Image"
)

        image_button = gr.Button(
        "😎 Analyze Emotion"
)

        image_output = gr.Textbox(
        label="🧠 Face Emotion"
)

        image_button.click(
        fn=detect_face_emotion,
        inputs=image_input,
        outputs=image_output
)

    # AI COACH
    with gr.Tab("🤖 AI Coach"):

        chatbot_input = gr.Textbox(
        lines=5,
        label="Ask AI Coach"
)

        chatbot_button = gr.Button(
        "🤖 Ask"
)

        chatbot_output = gr.Textbox(
        lines=10,
        label="AI Coach Response"
)

        chatbot_button.click(
        fn=ai_chatbot,
        inputs=chatbot_input,
        outputs=chatbot_output
)

    # TIMETABLE
    with gr.Tab("📅 Timetable Generator"):

        timetable_hours = gr.Number(
        label="📚 Study Hours"
)

        timetable_button = gr.Button(
        "📅 Generate"
)

        timetable_output = gr.Textbox(
        lines=15,
        label="📅 Timetable"
)

        timetable_button.click(
        fn=generate_timetable,
        inputs=timetable_hours,
        outputs=timetable_output
)

    # RESUME ANALYZER
    with gr.Tab("📄 Resume Analyzer"):

        resume_input = gr.File(
        label="📄 Upload Resume"
)

        resume_button = gr.Button(
        "📄 Analyze Resume"
)

        resume_output = gr.Textbox(
        lines=15,
        label="📋 Resume Analysis"
)

        resume_button.click(
        fn=analyze_resume,
        inputs=resume_input,
        outputs=resume_output
)

    # REGISTER
    with gr.Tab("🔐 Register"):

        username = gr.Textbox(
        label="👤 Username"
)

        password = gr.Textbox(
        label="🔑 Password",
        type="password"
)

        register_button = gr.Button(
        "✅ Register"
)

        register_output = gr.Textbox(
        label="📋 Status"
)

        register_button.click(
        fn=register,
        inputs=[
            username,
            password
        ],
        outputs=register_output
)

    # VOICE ASSISTANT
    with gr.Tab("🎤 Voice Assistant"):

        voice_button = gr.Button(
        "🎤 Start Assistant"
)

        voice_output = gr.Textbox(
        lines=5,
        label="🎤 Voice Assistant"
)

        voice_button.click(
        fn=voice_assistant,
        outputs=voice_output
)

# =========================================================

# LAUNCH

# =========================================================

interface.launch(share=True)

!pip install google-generativeai

import google.generativeai as genai

genai.configure(
api_key="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"
)

model = genai.GenerativeModel(
    "gemini-1.5-flash"
)

def ai_chatbot(user_question):
    prompt = f"""
You are MoodMind AI Coach.

Give motivational, career,
productivity, study, and
stress-management advice.

User Question:
{user_question}
"""

    response = model.generate_content(
        prompt
    )

    return response.text

def career_ai(career_goal):
    prompt = f"""
Create a roadmap for:
{career_goal}

Include:
- skills
- projects
- salary
- future scope
"""

    response = model.generate_content(
        prompt
    )

    return response.text

def analyze_resume_ai(text):
    prompt = f"""
Analyze this resume.

Give:
- strengths
- weaknesses
- ATS score
- improvement tips

Resume:
{text}
"""

    response = model.generate_content(
        prompt
    )

    return response.text

import os

os.environ["GEMINI_API_KEY"] = "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"

genai.configure(
api_key=os.getenv("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")
)

# @title
interface.launch(share=True)
